name: Test tracing-tracy

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
    paths:
    - 'tracing-tracy/**'
    - '.github/workflows/tracing-tracy.yml'
    - '!tracing-tracy/**.mkd'
    - '!tracing-tracy/LICENSE-*'
  pull_request:
    types: [opened, repoened, synchronize]

jobs:
  native-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        rust_toolchain: [nightly, stable, 1.53.0]
        os: [ubuntu-latest, windows-latest, macOS-latest]
        flags: ["", "--release", "--no-default-features", "--all-features"]
    timeout-minutes: 20
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
            submodules: 'recursive'
      - name: Install Rust ${{ matrix.rust_toolchain }}
        uses: actions-rs/toolchain@v1
        with:
            toolchain: ${{ matrix.rust_toolchain }}
            profile: minimal
            default: true
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path=tracing-tracy/Cargo.toml ${{ matrix.flags }} -- --nocapture
        env:
          TRACY_NO_INVARIANT_CHECK: 1
